import React from 'react';

export const accounts = <i className="fa fa-solid fa-house custom-icon"></i>;
export const aiIcon = <i className="fa fa-solid fa-robot custom-icon"></i>;
export const airplane = <i className="fa fa-sharp fa-solid fa-plane custom-icon"></i>;
export const barChart = <i className="fa fa-sharp fa-solid fa-chart-column custom-icon"></i>;
export const bell = <i className="fa fa-solid fa-bell custom-icon"></i>;
export const billboard = <i className="fa-solid fa-billboard custom-icon"></i>;
export const bitcoin = <i className="fa fa-solid fa-bitcoin-sign custom-icon"></i>;
export const budgetIcon = <i className="fas fa-wallet custom-icon"></i>;
export const business = <i className="fa-regular fa-buildings custom-icon"></i>;
export const calendar = <i className="fa fa-sharp fa-calendars custom-icon"></i>;
export const card = <i className="fa fa-sharp fa-solid fa-credit-card custom-icon"></i>;
export const categories = <i className="fa fa-solid fa-house custom-icon"></i>;
export const certificate = <i className="fa-solid fa-file-certificate custom-icon"></i>;
export const circle = <i className="fa fa-thin fa-circle custom-icon"></i>;
export const coaching = <i className="fa-sharp fa-solid fa-chalkboard custom-icon"></i>;
export const commDollar = <i className="fa-solid fa-comments-dollar custom-icon"></i>;
export const comment = <i className="fa fa-light fa-comment custom-icon"></i>;
export const cryptoIcon = <i className="fa fa-bitcoin custom-icon"></i>;
export const dashboard = <i className="fa fa-solid fa-house custom-icon"></i>;
export const depreciation = <i className="fa-solid fa-chevrons-down custom-icon"></i>;
export const distribution = <i className="fa-solid fa-building-circle-arrow-right custom-icon"></i>;
export const dollar = <i className="fa fa-sharp fa-light fa-dollar-sign custom-icon"></i>;
export const email = <i className="fa-sharp fa-regular fa-envelopes custom-icon"></i>;
export const euro = <i className="fa fa-light fa-euro-sign custom-icon"></i>;
export const event = <i className="fa-regular fa-calendar-users custom-icon"></i>;
export const expenses = <i className="fa fa-sharp fa-light fa-cart-shopping custom-icon"></i>;
export const freelance = <i className="fa fa-solid fa-house custom-icon"></i>;
export const gift = <i className="fa-solid fa-gift custom-icon"></i>;
export const glob = <i className="fa-regular fa-globe custom-icon"></i>;
export const graduationCap = <i className="fa-solid fa-graduation-cap custom-icon"></i>;
export const groceries = <i className="fa-solid fa-groceries custom-icon"></i>;
export const handsHeart = <i className="fa-solid fa-hands-heart custom-icon"></i>;
export const healthCheckIcon = <i className="fa fa-heartbeat custom-icon"></i>;
export const investmentsIcon = <i className="fa fa-hand-holding-usd custom-icon"></i>;
export const invoice = <i className="fa fa-sharp fa-light fa-file-invoice custom-icon"></i>;
export const lineChart = <i className="fa fa-solid fa-chart-line custom-icon trend-icon"></i>;
export const logout = <i className="fa fa-sharp fa-solid fa-arrow-right-from-bracket custom-icon"></i>;
export const marketing = <i className="fa-duotone fa-chart-simple custom-icon"></i>;
export const money = <i className="fa fa-sharp fa-light fa-money-bill custom-icon"></i>;
export const newspaper = <i className="fa fa-solid fa-newspaper custom-icon"></i>;
export const partnership = <i className="fa-solid fa-handshake custom-icon"></i>;
export const pieChart = <i className="fa fa-solid fa-chart-pie custom-icon"></i>;
export const piggy = <i className="fa fa-sharp fa-light fa-piggy-bank custom-icon"></i>;
export const plus = <i className="fa fa-thin fa-plus custom-icon"></i>;
export const recipt = <i className="fa fa-light fa-receipt custom-icon"></i>;
export const rental = <i className="fa fa-solid fa-paperclip custom-icon"></i>;
export const savingsIcon = <i className="fas fa-piggy-bank custom-icon"></i>;
export const services = <i className="fa-light fa-money-bill-transfer custom-icon"></i>;
export const settings = <i className="fa fa-thin fa-sliders custom-icon"></i>;
export const shoppingBag = <i className="fa fa-solid fa-shopping-bag custom-icon"></i>;
export const singout = <i className="fa fa-light fa-right-from-bracket custom-icon"></i>;
export const spa = <i className="fa fa-solid fa-spa custom-icon"></i>;
export const stocks = <i className="fa fa-solid fa-arrow-trend-up custom-icon"></i>;
export const trading = <i className="fa-regular fa-display-chart-up-circle-dollar custom-icon"></i>;
export const transaction = <i className="fa fa-sharp fa-regular fa-money-from-bracket custom-icon"></i>;
export const trash = <i className="fa fa-sharp fa-light fa-trash custom-icon"></i>;
export const travel = <i className="fa-sharp fa-solid fa-plane custom-icon"></i>;
export const trend = <i className="fa fa-sharp fa-light fa-money-bill-trend-up custom-icon"></i>;
export const user = <i className="fa fa-thin fa-user custom-icon"></i>;
export const utensils = <i className="fa fa-solid fa-utensils custom-icon"></i>;
export const water = <i className="fa fa-solid fa-water custom-icon"></i>;
export const gas = <i className="fa fa-solid fa-gas-pump custom-icon"></i>;
export const electricity = <i className="fa fa-solid fa-bolt custom-icon"></i>;
export const fire = <i className="fa fa-solid fa-fire custom-icon"></i>;
